### ISSUE TITLE
TemplateDoesNotExist at /login/

### ISSUE THREAD

**Issue by mhaddoudi** [smahesh29/Django-WebApp#14]
Hello!
How can I solve this issue please, whenever I click on log in or sign up. I have this error displayed 

TemplateDoesNotExist at /login/
bootstrap4/uni_form.html

**Comment by sraonekumar** [comment]
Just Removed " {{ form|crispy }}" in users/login.html template and updated with only " {{ form }}" it worked .

**Comment by mhaddoudi** [comment]
Thanks a lot, it worked!!
I couldn't find out why. Have a nice day!
