### ISSUE TITLE
Django update

### ISSUE THREAD

**Issue by knc6** [smahesh29/Django-WebApp#2]
Change django_web_app/blog/templates/blog/base.html from {% load staticfiles %} to {% load static %}, else it gives the error: django.template.exceptions.TemplateSyntaxError: 'staticfiles' is not a registered tag library.

**Comment by MohanChhabaria** [comment]
@knc6  I have made the changes as mentioned and made a pull request for the same.

**Comment by smahesh29** [comment]
The project is developed using Django v2, so if you use Django v2 and run the project then it will not give any error. If you are using Django v3 then only you need to make changes in base.html

**Comment by vedant11** [comment]
> The project is developed using Django v2, so if you use Django v2 and run the project then it will not give any error. If you are using Django v3 then only you need to make changes in base.html

Don't you think it'd be a good work to rebase your project to python3?
